name: Formats

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Formats P${{ matrix.php }} ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2, prestissimo
        coverage: pcov

    - name: Install Composer dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-progress

    - name: Coding Style Checks
      run: |
           vendor/bin/rector process src --dry-run
           vendor/bin/php-cs-fixer fix -v --allow-risky=yes --dry-run

    - name: Type Checks
      run: vendor/bin/phpstan analyse
